apiVersion: v1
kind: Service
metadata:
  name: java-sample-app-svc
  labels:
    app: java-sample-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: java-sample-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-sample-app-deploy
  labels:
    app: java-sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-sample-app
  template:
    metadata:
      labels:
        app: java-sample-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - arm64
      containers:
      - name: java-sample-app
        image: nginx:latest
        ports:
        - containerPort: 8080
        env:
        - name: dbmode
          value: inMem
        - name: COMPlus_PerfMapEnabled
          value: '1'
        - name: COMPlus_EnableEventLog
          value: '1'
        resources:
          requests:
            memory: "2048Mi"
            cpu: "1"
          limits:
            memory: "2048Mi"
            cpu: "1"
